[pytest]
# Discover tests only in these folders
testpaths =
    tests/unit
    tests/integration

# Pytest + coverage options
addopts =
    -ra
    --strict-markers
    --disable-warnings
    --maxfail=1
    --cov=app
    --cov-branch
    --cov-report=term-missing
    --cov-report=xml
    --cov-fail-under=70
    --no-cov-on-fail
    --cov-config=.coveragerc