version: 2.1
setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.5

# Flags toggled by path-filtering
parameters:
  run-tests:
    type: boolean
    default: false
  run-build-deploy:
    type: boolean
    default: false

workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          name: set-pipeline-flags
          base-revision: << pipeline.git.base_revision >>
          config-path: .circleci/continuation.yml
          # <regex> <pipeline param> <value>
          mapping: |
            ^(app|src|Dockerfile|requirements.*|setup\.cfg|pyproject\.toml)\b run-tests true
            ^(app|src|Dockerfile|requirements.*|setup\.cfg|pyproject\.toml)\b run-build-deploy true
            ^tests/.*                                         run-tests true
            ^\.circleci/.*                                    run-tests true
            ^\.circleci/.*                                    run-build-deploy true
            ^(README\.md|docs/.*)                             run-tests false
            ^(README\.md|docs/.*)                             run-build-deploy false