version: 2.1
setup: true

orbs:
  path-filtering: circleci/path-filtering@1.1.0

workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          base-revision: HEAD~1
          config-path: .circleci/continue.yml
          mapping: |
            .* run-tests true
            .* run-build-deploy true
          # Use a newer base image with Python 3.9+
          image: cimg/python:3.11